sudo: required
dist: trusty
language: node_js

node_js:
  - "stable"
  - "14"
  - "12"
  - "10"
  - "8"
  - "6"
  - "4"
  - "0.12"
  - "0.10"

script:
  - >
    nodeVersionMajor=`node -e "console.log(process.versions.node.split('.')[0])"`;

    if [ $nodeVersionMajor -ge 10 ]; then
      npm test;
    else
      # install old mocha for old nodejs versions
      npm install mocha@3;
      npm test;
    fi;
